# Generated by Django 5.0.2 on 2024-03-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='r_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='s_status',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('contact', models.IntegerField()),
                ('b_status', models.IntegerField()),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.services')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
            ],
        ),
    ]
