# Generated by Django 5.0.2 on 2024-03-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
