from django.urls import path
from . import views
urlpatterns = [
    path('',views.homepage,name="home"),
    path('signup',views.signuppage,name="signup"),
    path('insertinfo',views.insertinfo,name="insertinfo"),
    path('login',views.loginpage,name="login"),
    path('singleservice/<int:sid>',views.singleservice,name="singleservice"),
    path('services',views.servicepage,name="service"),
    path('addservices',views.addservices,name="addservices"),
    path('insertser',views.insertser,name="insertser"),
    path('checkuserinfo',views.checkuserinfo,name="checkuserinfo"),
    path('logout',views.logout,name="logout"),
    path('manageservice',views.manageservice,name="manageservice"),
    path('delete/<int:id>',views.deletepage,name="delete"),
    path('bookingpage',views.bookingpage,name="bookingpage"),
    path('managebooking',views.managebooking,name="managebooking"),
    path('rejectbooking/<int:id>',views.rejectbooking,name="rejectbooking"),
    path('booking',views.book,name="booking"),
    path('about',views.aboutpage,name="about"),
    path('contact',views.contactpage,name="contact"),
    path('contactdata',views.contactdata,name="contactdata"),
    path('cancelbooking/<int:id>',views.cancelbooking,name="cancelbooking"),
    path('feedbackpage/<int:id>',views.feedbackpage,name="feedbackpage"),
    path('insertfeed',views.insertfeed,name="insertfeed"),
    path('forgot',views.forgotpage,name="forgot"),
    path('forgotpassword',views.forgotpassword,name="forgotpassword"),
    path('editservice/<int:id>',views.editservice,name="editservice"),
    path('updatedata',views.updatedata,name="updatedata"),
]